skip_branch_with_pr: true
build: off
version: "{build}"

# cache:
#   - '%APPDATA%\npm-cache -> package-lock.json'
#   - node_modules -> package-lock.json

install:
  - ps: $env:GOBIN = "$($env:GOPATH)\bin;"
  - ps: $env:PATH += $env:GOBIN
  - go run bootstrap.go
  - go env

test_script:
  - echo %PATH%
  - set
  - go env
  - mage test

# after_test:
#   - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\.testresults\junit.xml))
