skip_branch_with_pr: true
build: off
version: "{build}"
branches:
  only:
    - master

cache:
  - c:\users\appveyor\go -> go.mod, go.sum, scripts\setup.go

install:
  - ps: $env:GOBIN = "$(go env GOPATH)\bin"
  - ps: $env:PATH += ";$($env:GOBIN);"
#   - go run .\scripts\setup.go
  - go get github.com/magefile/mage
  - mage setup

test_script:
#   - task ci
  - mage test

after_test:
#   - ps: Get-ChildItem -Path .\.testresults
#   - ps: cat .testresults\junit.xml
  - ps: echo $env:APPVEYOR_JOB_ID
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .testresults\junit.xml))
