skip_branch_with_pr: true
build: off
version: "{build}"
branches:
  only:
    - master

cache:
  - c:\users\appveyor\go -> magefile.go, go.mod, go.sum

install:
  - ps: $env:GOBIN = "$(go env GOPATH)\bin"
  - ps: $env:PATH += ";$($env:GOBIN);"
  - go run .\scripts\setup.go

test_script:
  - task coverage

after_test:
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\.testresults\junit.xml))
