version: 2
jobs:
  go1.11:
    docker:
      - image: circleci/golang:1.11

    working_directory: ~/captain-githook

    steps:
      - checkout
      - run:
          name: install mage
          command: |
            git clone git@github.com:magefile/mage ~/mage
            ls -R ~/
      - run: go test -v ./pkg/...

workflows:
  version: 2
  ci:
    jobs:
      - go1.11