trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: GoTool@0
  displayName: 'Use Go 1.15'
  inputs5
    version: 1.12

- script: |
    export GOPATH=$(go env GOPATH)
    PATH=$PATH:$GOPATH/bin
    curl -sL https://taskfile.dev/install.sh | sh -s -- -b $GOPATH/bin
    task setup
  displayName: 'Install dependencies'

- script: |
    export GOPATH=$(go env GOPATH)
    PATH=$PATH:$GOPATH/bin
    task lint
  displayName: 'Run golint'
