trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    go run ./scripts/setup.go
  displayName: 'Install dependencies'

- script: |
    task lint
  displayName: 'Run golint'
